name: Determine responsibilities for the week

on:
  workflow_dispatch:

jobs:
  post-to-Discord:
    runs-on: ubuntu-latest
    steps:
      - name: Discord post action step
        id: discord
        uses: AAU-Dat/automate-team-responsibilities@v1.5
        with:
          team: '["Oliver", "Andreas", "Tobias", "Elias", "Raymond", "Lars", "Daniel"]'
          responsibilities: '[{"name": "Scrum master 1", "random": false}, {"name": "Scrum master 2", "random": true}, {"name": "Cake", "random": false}, {"name": "Fruit", "random": false}, {"name": "Drinks", "random": false}]'
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
