name: Determine scrum masters for the week

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  post-to-Discord:
    runs-on: ubuntu-latest
    steps:
      - name: Discord post action step
        id: discord
        uses: AAU-Dat/automate-team-responsibilities@v0.2
        with:
          team: '["Daniel", "Lars", "Raymond", "Elias", "Tobias", "Andreas", "Oliver"]'
          responsibilities: '[{"name": "Scrum master", "number": 1}, {"name": "Cake", "number": 1}, {"name": "Drinks", "number": 1}]'
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
